// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qesziqweohdkynlvvpzm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFlc3ppcXdlb2hka3lubHZ2cHptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxNTM3NDUsImV4cCI6MjA1NzcyOTc0NX0.E9z8h2q-RvvwkBUkfWtVGHHet4hjkS8bd1VSdil6__0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);